### ISSUE TITLE
Connection Failing

### ISSUE THREAD

**Issue by s7bruce** [domalab/homebridge-ventair-ceiling-fan#1]
Please help, I am new to the whole homebridge system and trying to configure my fan and get the following in the logs of homebridge:

[15/08/2024, 12:05:18 am] [Skyfan DC Ceiling Fan] Retry in 1 minute
[15/08/2024, 12:05:18 am] [Skyfan DC Ceiling Fan] Connection failed Error: connect ECONNREFUSED "my ip":6668
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '"my ip"',
  port: 6668
}

I followed the instructions that were linked and I think I have everything right in the config

**Comment by domalab** [comment]
Not sure how your setup is but I have my homebridge instance and ventair skyfan dc ceiling fans on the same network. 

I have experienced issues If you have home assistant on the same network and use local tuya integration to control fans then it blocks it.

**Comment by s7bruce** [comment]
I have a windows pc running homebridge connected by wifi with my fan on the same network, no instances of home assistant at all but not sure how i can tell how my tuya is connected

**Comment by domalab** [comment]
Have you tried disabling local firewall on your windows pc? 

Your local PC you are using to run the scan may be blocking incoming UDP traffic if you have a local security software or firewall - see if you can turn it off to test (or allow port 6666 and 6667 UDP traffic), or try another machine.
Make sure you are not running the SmartLife app - it can cause the device to block connections and disable broadcasts.

**Comment by s7bruce** [comment]
Have tried adding rules for ports that are recommended and turning off firewall completely and still nothing, in saying that the fan and light is showing in the accessories tab in homebridge but not responding when pressed.
Have the fan connected to the tuya app on my phone and are showing correctly in the tuya developer platform

**Comment by domalab** [comment]
Not sure to be honest. I have a few of these ceiling fans in my house with wifi module and working without issues

[https://www.lightingillusions.com.au/product/white-ventair-skyfan-60-1500mm-3-blade-dc-ceiling-fan-and-remote-20137](url)

The error suggests that Homebridge is unable to connect to your fan's IP address on port 6668.
The specific error "ECONNREFUSED" typically means that either the device is not listening on that port, or a firewall is blocking the connection.

You can run a network scan to see which ports are open on the fan/s

**Comment by s7bruce** [comment]
How can I check what port it is on?
As firewall is completely off
